export const scoringCriteria = [
  { id: 'quartier', label: 'Quartier / ambiance' },
  { id: 'calme_voisinage', label: 'Calme / voisinage' },
  { id: 'mitoyennete', label: 'Mitoyenneté' },
  { id: 'humidite_eau', label: 'Humidité / eaux pluviales' },
  { id: 'etat_technique', label: 'État technique global' },
  { id: 'chaudiere', label: 'Chaudière / chauffage' },
  { id: 'jardin', label: 'Jardin / extérieur' },
  { id: 'luminosite', label: 'Luminosité' },
  { id: 'projection_famille', label: 'Projection avec ma fille' },
  { id: 'envie_vivre', label: "Envie réelle d'y vivre" },
  { id: 'preference_autre_bien', label: "Préférence vs l'autre bien" },
];

const yesNo = (noSeverity = 'red') => [
  { value: 'oui', label: 'Oui' },
  { value: 'non', label: 'Non', severity: noSeverity },
];

const yesNoGoodNo = [
  { value: 'oui', label: 'Oui', severity: 'red' },
  { value: 'non', label: 'Non' },
];

const yesWarnNo = [
  { value: 'oui', label: 'Oui', severity: 'warning' },
  { value: 'non', label: 'Non' },
];

const neutralYesNo = [
  { value: 'oui', label: 'Oui' },
  { value: 'non', label: 'Non' },
];

const yesBofNo = [
  { value: 'oui', label: 'Oui' },
  { value: 'bof', label: 'Bof', severity: 'warning' },
  { value: 'non', label: 'Non', severity: 'red' },
];

const okDoubtBad = [
  { value: 'ok', label: 'OK' },
  { value: 'doute', label: 'Doute', severity: 'warning' },
  { value: 'mauvais', label: 'Mauvais', severity: 'red' },
];

const weakMediumStrongRisk = [
  { value: 'faible', label: 'Faible' },
  { value: 'moyen', label: 'Moyen', severity: 'warning' },
  { value: 'fort', label: 'Fort', severity: 'red' },
];

const goodMediumWeak = [
  { value: 'bonne', label: 'Bonne' },
  { value: 'moyenne', label: 'Moyenne', severity: 'warning' },
  { value: 'faible', label: 'Faible', severity: 'red' },
];

const lowMediumHighMaintenance = [
  { value: 'faible', label: 'Faible' },
  { value: 'moyen', label: 'Moyen', severity: 'warning' },
  { value: 'eleve', label: 'Élevé', severity: 'warning' },
];

const blockerField = (id) => ({
  id,
  type: 'choice',
  label: 'Bloquant immédiat ?',
  required: false,
  important: true,
  blocksDecision: true,
  options: yesNoGoodNo,
});

const proofFields = (id, label) => [
  {
    id: `preuve_oral_${id}`,
    type: 'choice',
    label: `Oralement rassuré : ${label}`,
    options: neutralYesNo,
  },
  {
    id: `preuve_ecrit_${id}`,
    type: 'choice',
    label: `Preuve écrite reçue : ${label}`,
    required: true,
    options: yesNo('warning'),
  },
];

export const quickBlockers = [
  { id: 'quick_bruit_voisinage', type: 'choice', label: 'Bruit / voisinage', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_mitoyennete_sejour', type: 'choice', label: 'Mitoyenneté séjour', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_mitoyennete_chambres', type: 'choice', label: 'Mitoyenneté chambres', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_humidite_odeur', type: 'choice', label: 'Humidité / odeur', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_facade_eaux', type: 'choice', label: 'Façade / traces noires / eaux pluviales', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_chaudiere', type: 'choice', label: 'Chaudière : année + entretien clairs', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_charges', type: 'choice', label: 'Charges ASL / lotissement', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_clauses', type: 'choice', label: 'Clauses revente / location future', important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_offre', type: 'choice', label: "Date limite offre / ordre d'arrivée", important: true, blocksDecision: true, options: okDoubtBad },
  { id: 'quick_preference_autre_bien', type: 'choice', label: "Préférence réelle vs l'autre bien", important: true, blocksDecision: true, options: okDoubtBad },
];

export const photoChecklist = [
  { id: 'photo_facade_avant', type: 'choice', label: 'Façade avant', options: yesNo('warning') },
  { id: 'photo_facade_jardin', type: 'choice', label: 'Façade jardin', options: yesNo('warning') },
  { id: 'photo_bas_mur_noirci', type: 'choice', label: 'Bas de mur noirci', options: yesNo('warning') },
  { id: 'photo_gouttieres', type: 'choice', label: 'Gouttières / descentes', options: yesNo('warning') },
  { id: 'photo_dalle_evacuation', type: 'choice', label: 'Dalle / évacuation eau', options: yesNo('warning') },
  { id: 'photo_chaudiere_plaque', type: 'choice', label: 'Chaudière + plaque modèle', options: yesNo('warning') },
  { id: 'photo_tableau_electrique', type: 'choice', label: 'Tableau électrique', options: yesNo('warning') },
  { id: 'photo_garage_sol_murs', type: 'choice', label: 'Garage sol / murs', options: yesNo('warning') },
  { id: 'photo_murs_mitoyens', type: 'choice', label: 'Murs mitoyens', options: yesNo('warning') },
  { id: 'photo_vmc_sdb', type: 'choice', label: 'VMC salle de bain', options: yesNo('warning') },
  { id: 'photo_fissures', type: 'choice', label: 'Fissures éventuelles', options: yesNo('warning') },
  { id: 'photo_jardin_visavis', type: 'choice', label: 'Jardin / vis-à-vis', options: yesNo('warning') },
];

export const sections = [
  {
    id: 'avant_arriver',
    number: '0',
    title: "Avant d'arriver",
    critical: true,
    badge: 'Mental',
    intro: "Répartis les rôles et pose le cadre : ce bien doit convaincre. Ne viens pas chercher des excuses pour acheter.",
    reminders: [
      "Demander à l'accompagnant d'être dur sur les défauts techniques.",
      "Garder en tête : ce bien doit me convaincre, pas l'inverse.",
    ],
    fields: [
      {
        id: 'roles_repartis',
        type: 'choice',
        label: 'Rôles répartis clairement ?',
        required: true,
        options: yesNo('warning'),
      },
      {
        id: 'collegue_dur',
        type: 'choice',
        label: "L'accompagnant sait qu'il doit signaler les points inquiétants ?",
        required: true,
        options: yesNo('warning'),
      },
      {
        id: 'phrase_garde_fou',
        type: 'choice',
        label: 'Phrase garde-fou validée avant de sortir de la voiture ?',
        required: true,
        options: yesNo('warning'),
      },
      {
        id: 'note_avant_arriver',
        type: 'textarea',
        label: "Note mentale avant visite",
        placeholder: "Ce que je refuse de minimiser aujourd'hui.",
        important: true,
      },
    ],
  },
  {
    id: 'lotissement',
    number: '1',
    title: 'En arrivant dans le lotissement',
    critical: true,
    badge: 'Voisinage',
    intro: "Observe avant d'entrer. Si le premier ressenti est mauvais, note-le sans rationaliser.",
    innerQuestion: 'Est-ce que je serais content de rentrer ici tous les soirs avec ma fille ?',
    fields: [
      { id: 'rue_calme', type: 'choice', label: 'Rue calme ?', required: true, options: yesNo('red') },
      { id: 'stationnement_facile', type: 'choice', label: 'Stationnement facile ?', required: true, options: yesNo('warning') },
      { id: 'maisons_entretenues', type: 'choice', label: 'Maisons autour bien entretenues ?', required: true, options: yesNo('warning') },
      {
        id: 'ambiance_lotissement',
        type: 'choice',
        label: 'Ambiance du lotissement',
        required: true,
        options: [
          { value: 'rassurante', label: 'Rassurante' },
          { value: 'moyenne', label: 'Moyenne', severity: 'warning' },
          { value: 'bof', label: 'Bof', severity: 'red' },
        ],
      },
      { id: 'bruit_exterieur', type: 'text', label: 'Bruit route / enfants / voisins ?', placeholder: 'Ce que j’entends vraiment.', important: true },
      { id: 'vis_a_vis_general', type: 'choice', label: 'Vis-à-vis général', required: true, options: weakMediumStrongRisk },
      { id: 'feeling_immediat', type: 'scale', label: 'Feeling immédiat', required: true },
      {
        id: 'ressenti_mauvais_note',
        type: 'textarea',
        label: 'Si le ressenti est mauvais, pourquoi ?',
        placeholder: "Ne lisse pas ton ressenti. Note ce qui dérange.",
        important: true,
      },
      blockerField('bloquant_lotissement'),
    ],
  },
  {
    id: 'exterieur',
    number: '2',
    title: "Extérieur maison avant d'entrer",
    critical: true,
    badge: 'Technique',
    intro: "Regarde façade, fissures, eau et jardin avant d'être influencé par l'intérieur.",
    reminders: [
      'Red flag : fissure en escalier, fissure large, enduit gonflé, mur humide.',
      "L'eau contre la façade est un point technique prioritaire.",
    ],
    fields: [
      { id: 'fissures_facade', type: 'choice', label: 'Fissures façade', required: true, options: okDoubtBad },
      { id: 'fissures_escalier', type: 'choice', label: 'Fissures en escalier', required: true, options: okDoubtBad },
      { id: 'enduit_effrite', type: 'choice', label: "Enduit qui s'effrite", required: true, options: okDoubtBad },
      { id: 'bas_facade_noirci', type: 'choice', label: 'Bas de façade noirci', required: true, options: okDoubtBad },
      { id: 'traces_sous_gouttiere', type: 'choice', label: 'Traces sous gouttière', required: true, options: okDoubtBad },
      { id: 'mur_mitoyen_exterieur', type: 'choice', label: 'Mur mitoyen extérieur propre', required: true, options: okDoubtBad },
      {
        id: 'note_fissures_facade',
        type: 'textarea',
        label: 'Notes façade / fissures',
        placeholder: 'Localisation, largeur, forme, photos à reprendre.',
        important: true,
      },
      { id: 'dalle_penche_maison', type: 'choice', label: 'Dalle qui penche vers la maison', required: true, options: okDoubtBad },
      { id: 'eau_stagne_facade', type: 'choice', label: 'Eau pouvant stagner contre le mur', required: true, options: okDoubtBad },
      { id: 'gouttieres_propres', type: 'choice', label: 'Gouttières propres', required: true, options: okDoubtBad },
      { id: 'descente_gouttiere_raccordee', type: 'choice', label: 'Descente de gouttière bien raccordée', required: true, options: okDoubtBad },
      { id: 'traces_debordement', type: 'choice', label: 'Traces de débordement', required: true, options: okDoubtBad },
      { id: 'evacuation_visible', type: 'choice', label: 'Caniveau / évacuation visible', required: true, options: okDoubtBad },
      {
        id: 'note_eau_gouttieres',
        type: 'textarea',
        label: 'Réponse vendeur sur eaux pluviales / traces noires',
        placeholder: "Réseau collectif, puits perdu, infiltration, problème passé, dégât des eaux.",
        important: true,
      },
      { id: 'jardin_exploitable', type: 'scale', label: 'Jardin exploitable', required: true },
      { id: 'intimite_jardin', type: 'scale', label: 'Intimité du jardin', required: true },
      { id: 'bruit_jardin', type: 'scale', label: 'Calme dans le jardin', required: true },
      { id: 'vis_a_vis_jardin', type: 'choice', label: 'Vis-à-vis jardin', required: true, options: weakMediumStrongRisk },
      { id: 'entretien_jardin', type: 'choice', label: 'Entretien à prévoir', required: true, options: lowMediumHighMaintenance },
      { id: 'enfant_joue_jardin', type: 'choice', label: 'Ma fille pourrait y jouer facilement ?', required: true, options: yesNo('red') },
      {
        id: 'note_jardin',
        type: 'textarea',
        label: 'Le jardin est-il un vrai plus ?',
        placeholder: 'Vrai plus quotidien ou petit extérieur moyen ?',
        important: true,
      },
      blockerField('bloquant_exterieur'),
    ],
  },
  {
    id: 'entree',
    number: '3',
    title: 'Entrée dans la maison',
    critical: true,
    badge: 'Ressenti',
    intro: "Ne parle pas tout de suite. Ressens. Une odeur humide ou un malaise immédiat compte vraiment.",
    fields: [
      { id: 'odeur_humidite_entree', type: 'choice', label: "Odeur d'humidité ?", required: true, options: yesNoGoodNo },
      { id: 'maison_renfermee', type: 'choice', label: 'Maison renfermée ?', required: true, options: yesNoGoodNo },
      { id: 'luminosite_generale', type: 'choice', label: 'Luminosité générale', required: true, options: goodMediumWeak },
      {
        id: 'bruit_interieur',
        type: 'choice',
        label: 'Bruit intérieur',
        required: true,
        options: [
          { value: 'calme', label: 'Calme' },
          { value: 'moyen', label: 'Moyen', severity: 'warning' },
          { value: 'genant', label: 'Gênant', severity: 'red' },
        ],
      },
      { id: 'premiere_projection', type: 'choice', label: 'Première projection', required: true, options: yesBofNo },
      {
        id: 'note_entree_ressenti',
        type: 'textarea',
        label: 'Ressenti immédiat honnête',
        placeholder: 'Odeur, froid, malaise, sensation saine ou non.',
        important: true,
      },
      blockerField('bloquant_entree'),
    ],
  },
  {
    id: 'sejour_cuisine',
    number: '4',
    title: 'Séjour / cuisine',
    critical: true,
    badge: 'Vie quotidienne',
    intro: 'Regarde les murs, plinthes, fenêtres, prises, carrelage, emplacement cuisine et coût pour rendre la pièce chaleureuse.',
    reminders: ['Fais 10 secondes sans parler dans le séjour.', 'Écoute voix, télé, impacts, route, jardin voisin, chaudière ou VMC.'],
    fields: [
      { id: 'sejour_agreable', type: 'choice', label: 'Séjour agréable ?', required: true, options: yesBofNo },
      { id: 'cuisine_utilisable', type: 'choice', label: 'Cuisine utilisable rapidement ?', required: true, options: yesNo('warning') },
      { id: 'peinture_refaire', type: 'choice', label: 'Peinture à refaire ?', required: true, options: yesNoGoodNo },
      { id: 'sol_correct', type: 'choice', label: 'Sol correct ?', required: true, options: yesNo('warning') },
      { id: 'mur_mitoyen_sejour', type: 'choice', label: 'Mur mitoyen dans cette pièce ?', required: true, options: yesNoGoodNo },
      { id: 'bruit_voisin_sejour', type: 'choice', label: 'Bruit voisin audible ?', required: true, options: yesNoGoodNo },
      { id: 'luminosite_sejour', type: 'choice', label: 'Luminosité suffisante ?', required: true, options: yesNo('warning') },
      {
        id: 'note_test_silence_sejour',
        type: 'textarea',
        label: 'Test silence séjour et mur mitoyen',
        placeholder: 'Ce que j’entends et quel mur est mitoyen exactement.',
        important: true,
      },
      blockerField('bloquant_sejour'),
    ],
  },
  {
    id: 'garage_technique',
    number: '5',
    title: 'Garage / cellier / local technique',
    critical: true,
    badge: 'Travaux',
    intro: "Le garage et la chaudière peuvent changer la valeur réelle du bien.",
    reminders: ["Si le garage est trop petit ou humide, ça baisse l'intérêt réel.", "Prendre la plaque chaudière en photo si possible."],
    fields: [
      { id: 'voiture_rentre_garage', type: 'choice', label: 'Voiture rentre vraiment ?', required: true, options: yesNo('red') },
      { id: 'rangement_garage', type: 'choice', label: 'Rangement suffisant ?', required: true, options: yesNo('warning') },
      { id: 'velos_outils_possible', type: 'choice', label: 'Vélos / outils possibles ?', required: true, options: yesNo('warning') },
      { id: 'humidite_sol_garage', type: 'choice', label: 'Humidité au sol ?', required: true, options: yesNoGoodNo },
      { id: 'traces_eau_garage', type: 'choice', label: "Traces d'eau ?", required: true, options: yesNoGoodNo },
      { id: 'fissures_garage', type: 'choice', label: 'Fissures au sol / murs ?', required: true, options: yesNoGoodNo },
      { id: 'porte_garage_ok', type: 'choice', label: 'Porte garage OK ?', required: true, options: yesNo('warning') },
      {
        id: 'note_garage',
        type: 'textarea',
        label: 'Notes garage',
        placeholder: 'Taille réelle, humidité, rangement, défauts qui diminuent la valeur.',
        important: true,
      },
      { id: 'annee_chaudiere', type: 'text', label: 'Année chaudière', placeholder: 'Année / modèle / photo plaque', important: true },
      { id: 'entretien_annuel_prouve', type: 'choice', label: 'Entretien annuel prouvé ?', required: true, options: yesNo('red') },
      { id: 'certificat_entretien', type: 'choice', label: "Dernier certificat disponible ?", required: true, options: yesNo('warning') },
      { id: 'eau_chaude_chaudiere', type: 'choice', label: 'Eau chaude via chaudière ?', required: true, options: yesNo('warning') },
      { id: 'factures_energie', type: 'choice', label: 'Factures énergie disponibles ?', required: true, options: yesNo('warning') },
      { id: 'chaudiere_origine', type: 'choice', label: "Chaudière d'origine ou très ancienne ?", required: true, options: yesNoGoodNo },
      { id: 'pannes_connues', type: 'choice', label: 'Pannes connues ?', required: true, options: yesNoGoodNo },
      {
        id: 'note_chaudiere',
        type: 'textarea',
        label: 'Notes chaudière / chauffage',
        placeholder: "Entretien, pannes, factures, remplacement 3k-6k à prévoir si historique flou.",
        important: true,
      },
      blockerField('bloquant_garage_technique'),
    ],
  },
  {
    id: 'escalier_etage',
    number: '6',
    title: 'Escalier / étage',
    critical: false,
    badge: 'Usage',
    intro: "Pendant que tu montes, vérifie la praticité réelle avec un enfant.",
    innerQuestion: 'Cette maison est-elle pratique au quotidien ou juste correcte sur papier ?',
    fields: [
      { id: 'escalier_stable', type: 'choice', label: 'Escalier stable', required: true, options: okDoubtBad },
      { id: 'rambarde_solide', type: 'choice', label: 'Rambarde solide', required: true, options: okDoubtBad },
      { id: 'fissures_angles_etage', type: 'choice', label: 'Fissures dans les angles', required: true, options: okDoubtBad },
      { id: 'bruits_etage', type: 'choice', label: 'Bruits venant voisin / extérieur', required: true, options: okDoubtBad },
      { id: 'circulation_enfant', type: 'choice', label: 'Circulation pratique avec enfant', required: true, options: okDoubtBad },
      {
        id: 'note_escalier_etage',
        type: 'textarea',
        label: 'Notes escalier / étage',
        placeholder: 'Ce qui rendrait le quotidien pénible.',
      },
    ],
  },
  {
    id: 'chambres',
    number: '7',
    title: 'Chambres',
    critical: true,
    badge: 'Calme',
    intro: 'Vérifie surtout calme, taille et projection. Fais 10 secondes de silence dans chaque chambre.',
    fields: [
      { id: 'lit_possible', type: 'choice', label: 'Chambre principale : lit 140/160 possible', required: true, options: yesNo('warning') },
      { id: 'placard_principal', type: 'choice', label: 'Chambre principale : placard / rangement', required: true, options: yesNo('warning') },
      { id: 'mur_mitoyen_principal', type: 'choice', label: 'Chambre principale : mur mitoyen', required: true, options: yesNoGoodNo },
      { id: 'bruit_principal', type: 'choice', label: 'Chambre principale : bruit audible', required: true, options: yesNoGoodNo },
      { id: 'luminosite_principale', type: 'choice', label: 'Chambre principale : luminosité', required: true, options: goodMediumWeak },
      { id: 'ressenti_principal', type: 'scale', label: 'Chambre principale : ressenti', required: true },
      { id: 'taille_chambre_enfant', type: 'choice', label: 'Chambre enfant : taille correcte', required: true, options: yesNo('red') },
      { id: 'chambre_enfant_rassurante', type: 'choice', label: 'Chambre enfant rassurante', required: true, options: yesNo('red') },
      { id: 'rangements_enfant', type: 'choice', label: 'Chambre enfant : rangements', required: true, options: yesNo('warning') },
      { id: 'calme_enfant', type: 'choice', label: 'Chambre enfant : calme', required: true, options: yesNo('red') },
      { id: 'lumineuse_enfant', type: 'choice', label: 'Chambre enfant lumineuse', required: true, options: yesNo('warning') },
      { id: 'projection_chambre_enfant', type: 'choice', label: 'Je vois bien ma fille ici ?', required: true, options: yesNo('red') },
      { id: 'vraie_chambre_3', type: 'choice', label: 'Troisième chambre vraiment exploitable', required: true, options: yesNo('warning') },
      { id: 'bureau_possible', type: 'choice', label: 'Bureau possible', required: true, options: yesNo('warning') },
      { id: 'rangement_chambre_3', type: 'choice', label: 'Rangement possible', required: true, options: yesNo('warning') },
      {
        id: 'note_silence_chambres',
        type: 'textarea',
        label: 'Test silence étage',
        placeholder: 'Bruit, mur mitoyen et note calme /10 pour chaque chambre.',
        important: true,
      },
      blockerField('bloquant_chambres'),
    ],
  },
  {
    id: 'salle_bain',
    number: '8',
    title: 'Salle de bain / WC',
    critical: true,
    badge: 'Humidité',
    intro: "La VMC, les joints, le plafond et l'odeur peuvent révéler un problème durable.",
    reminders: ['Test mouchoir devant VMC si possible : il doit être légèrement aspiré.'],
    fields: [
      { id: 'vmc_aspire', type: 'choice', label: 'VMC aspire correctement', required: true, options: okDoubtBad },
      { id: 'joints_propres', type: 'choice', label: 'Joints propres', required: true, options: okDoubtBad },
      { id: 'plafond_sain', type: 'choice', label: 'Plafond sain', required: true, options: okDoubtBad },
      { id: 'traces_humidite_sdb', type: 'choice', label: "Traces d'humidité", required: true, options: okDoubtBad },
      { id: 'odeur_humidite_sdb', type: 'choice', label: "Odeur d'humidité", required: true, options: okDoubtBad },
      { id: 'pression_eau', type: 'choice', label: "Pression d'eau", required: true, options: okDoubtBad },
      { id: 'evacuation_sdb', type: 'choice', label: 'Évacuation correcte', required: true, options: okDoubtBad },
      { id: 'etat_bain_douche', type: 'choice', label: 'État baignoire / douche', required: true, options: okDoubtBad },
      {
        id: 'note_sdb',
        type: 'textarea',
        label: 'Questions et notes salle de bain',
        placeholder: "VMC individuelle ? Problèmes d'humidité passés ? Résultat test mouchoir.",
        important: true,
      },
      blockerField('bloquant_salle_bain'),
    ],
  },
  {
    id: 'fenetres_isolation',
    number: '9',
    title: 'Fenêtres / volets / isolation',
    critical: true,
    badge: 'Isolation',
    intro: 'À faire dans 2 ou 3 pièces, pas forcément partout. Fenêtres fermées, écoute le bruit.',
    fields: [
      { id: 'double_vitrage', type: 'choice', label: 'Double vitrage', required: true, options: yesNo('warning') },
      { id: 'fenetres_ferment', type: 'choice', label: 'Fenêtres ferment bien', required: true, options: yesNo('warning') },
      { id: 'volets_fonctionnent', type: 'choice', label: 'Volets fonctionnent', required: true, options: yesNo('warning') },
      { id: 'joints_corrects', type: 'choice', label: 'Joints corrects', required: true, options: yesNo('warning') },
      { id: 'condensation_infiltration', type: 'choice', label: 'Traces condensation / infiltration', required: true, options: yesNoGoodNo },
      { id: 'bruit_fenetres_fermees', type: 'choice', label: 'Bruit extérieur fenêtres fermées', required: true, options: weakMediumStrongRisk },
      {
        id: 'note_fenetres',
        type: 'textarea',
        label: 'Notes fenêtres / isolation',
        placeholder: 'Pièces testées, bruit, condensation, joints, défauts.',
        important: true,
      },
      blockerField('bloquant_fenetres'),
    ],
  },
  {
    id: 'administratif',
    number: '10',
    title: 'Questions administratives à poser à la fin',
    critical: true,
    badge: 'Juridique',
    intro: "Attends la fin. Ne fais pas un interrogatoire avant d'avoir vu le bien, mais ne repars pas sans les réponses clés.",
    reminders: [
      "À ne pas quitter sans réponse : date limite offre, ordre d'arrivée, charges, clauses, taxe foncière, diagnostics.",
      'Pas écrit = pas sécurisé.',
    ],
    fields: [
      { id: 'date_limite_offre', type: 'text', label: "Date limite pour déposer une offre", placeholder: 'Date / heure / flou', important: true },
      { id: 'ordre_arrivee_offres', type: 'choice', label: "Offres traitées dans l'ordre d'arrivée ?", required: true, options: neutralYesNo },
      { id: 'analyse_date_commune', type: 'choice', label: 'Toutes les offres analysées après une date commune ?', required: true, options: yesNo('warning') },
      { id: 'residence_principale_obligation', type: 'choice', label: "Obligation d'occupation en résidence principale ?", required: true, options: yesWarnNo },
      { id: 'duree_occupation', type: 'text', label: "Durée minimale d'occupation", placeholder: 'Durée / aucune / flou', important: true },
      { id: 'clause_anti_speculation', type: 'choice', label: 'Clause anti-spéculation ?', required: true, options: yesNoGoodNo },
      { id: 'prix_revente_encadre', type: 'choice', label: 'Prix de revente encadré ?', required: true, options: yesNoGoodNo },
      { id: 'priorite_rachat_organisme', type: 'choice', label: "Priorité de rachat par l'organisme vendeur ?", required: true, options: yesNoGoodNo },
      { id: 'location_future_possible', type: 'choice', label: 'Location future possible si situation change ?', required: true, options: yesNo('warning') },
      { id: 'clauses_floues', type: 'choice', label: 'Clauses floues ou non écrites ?', required: true, options: yesNoGoodNo },
      {
        id: 'note_clauses',
        type: 'textarea',
        label: 'Notes clauses de vente / revente',
        placeholder: 'Ce qui bloque, ce qui est écrit, ce qui reste verbal.',
        important: true,
      },
      { id: 'asl_copro_charges', type: 'choice', label: 'ASL / copropriété horizontale / charges ?', required: true, options: yesWarnNo },
      { id: 'montant_charges_annuel', type: 'text', label: 'Montant annuel exact des charges', placeholder: 'Montant / inconnu', important: true },
      { id: 'reglement_lotissement', type: 'choice', label: 'Règlement de lotissement disponible ?', required: true, options: yesNo('warning') },
      { id: 'travaux_frais_communs', type: 'choice', label: 'Travaux ou frais communs prévus ?', required: true, options: yesNoGoodNo },
      { id: 'charges_floues', type: 'choice', label: 'Charges floues ou non prouvées ?', required: true, options: yesNoGoodNo },
      {
        id: 'note_charges',
        type: 'textarea',
        label: 'Notes charges / règlement',
        placeholder: 'Montant, espaces communs, voirie, éclairage, réseaux, frais à venir.',
        important: true,
      },
      { id: 'taxe_fonciere', type: 'text', label: 'Montant exact taxe foncière', placeholder: 'Montant / inconnu', important: true },
      { id: 'diagnostics_disponibles', type: 'choice', label: 'Diagnostics complets disponibles ?', required: true, options: yesNo('red') },
      { id: 'anomalies_gaz_elec', type: 'choice', label: 'Anomalies gaz ou électricité ?', required: true, options: yesNoGoodNo },
      { id: 'sinistres_connus', type: 'choice', label: 'Sinistres connus ?', required: true, options: yesNoGoodNo },
      { id: 'logement_vacant_depuis', type: 'text', label: 'Depuis quand le logement est vacant ?', placeholder: 'Durée / raison / flou', important: true },
      {
        id: 'note_diagnostics',
        type: 'textarea',
        label: 'Notes documents / diagnostics / fiscalité',
        placeholder: "Diagnostics, taxe foncière, sinistres, infiltration, assurance.",
        important: true,
      },
      ...proofFields('diagnostics', 'diagnostics'),
      ...proofFields('taxe_fonciere', 'taxe foncière'),
      ...proofFields('charges_asl', 'charges ASL'),
      ...proofFields('reglement_lotissement', 'règlement lotissement'),
      ...proofFields('clauses_revente_location', 'clauses revente / location'),
      ...proofFields('entretien_chaudiere', 'entretien chaudière'),
      ...proofFields('factures_energie', 'factures énergie'),
      ...proofFields('sinistres_infiltrations', 'sinistres / infiltrations'),
      blockerField('bloquant_administratif'),
    ],
  },
  {
    id: 'sortie_visite',
    number: '11',
    title: 'En sortant de la visite',
    critical: false,
    badge: 'Pression',
    intro: "Ne fais pas d'offre orale sous pression. Demande les documents avant de te positionner proprement.",
    reminders: [
      "Dire que l'intérêt est réel, mais qu'une offre sérieuse demande les éléments écrits.",
      "Si pression : préférer une offre sérieuse à une offre précipitée.",
    ],
    fields: [
      { id: 'pas_offre_orale', type: 'choice', label: "Aucune offre orale faite sous pression ?", required: true, options: yesNo('red') },
      { id: 'documents_demandes_sortie', type: 'choice', label: 'Documents demandés avant positionnement ?', required: true, options: yesNo('warning') },
      {
        id: 'note_sortie',
        type: 'textarea',
        label: 'Notes sortie de visite',
        placeholder: 'Réaction vendeur, pression éventuelle, documents promis.',
      },
    ],
  },
  {
    id: 'debrief',
    number: '12',
    title: "Débrief immédiat avec l'accompagnant",
    critical: true,
    badge: 'À froid',
    intro: 'À faire directement après, dans la voiture. Demande un avis froid et cherche ce que tu minimises.',
    fields: [
      { id: 'me_vois_vivre_ici', type: 'choice', label: 'Je me vois vivre ici avec ma fille ?', required: true, options: yesBofNo },
      { id: 'rassure_techniquement', type: 'choice', label: 'Je suis rassuré techniquement ?', required: true, options: yesBofNo },
      { id: 'voisinage_rassure', type: 'choice', label: 'Le voisinage me rassure ?', required: true, options: yesBofNo },
      {
        id: 'prefere_autre_bien',
        type: 'choice',
        label: "Je préfère ce bien à l'autre bien ?",
        required: true,
        options: [
          { value: 'oui', label: 'Oui' },
          { value: 'incertain', label: 'Incertain', severity: 'warning' },
          { value: 'non', label: 'Non', severity: 'warning' },
        ],
      },
      { id: 'pret_budget_mensuel', type: 'choice', label: 'Je suis prêt à payer 1 100-1 250 €/mois pour ça ?', required: true, options: yesNo('red') },
      { id: 'envie_rester_8_ans', type: 'choice', label: "J'ai envie d'y rester 8 ans minimum ?", required: true, options: yesNo('red') },
      {
        id: 'collegue_acheterait',
        type: 'choice',
        label: "Est-ce que l'accompagnant l'achèterait à ma place ?",
        required: true,
        options: [
          { value: 'oui', label: 'Oui' },
          { value: 'decote', label: 'Seulement avec décote', severity: 'warning' },
          { value: 'non', label: 'Non', severity: 'red' },
        ],
      },
      {
        id: 'prix_max_collegue',
        type: 'text',
        label: "Prix max que l'accompagnant mettrait à ma place",
        placeholder: 'Montant en euros',
        important: true,
      },
      {
        id: 'regret_minimise_6_mois',
        type: 'textarea',
        label: "Dans 6 mois, qu'est-ce que je pourrais regretter d'avoir minimisé ?",
        placeholder: 'Bruit, humidité, budget, clauses, voisinage, pression.',
        important: true,
      },
      {
        id: 'avis_collegue',
        type: 'textarea',
        label: "Avis froid de l'accompagnant",
        placeholder: "L'achèterait-il à ma place ? Défauts minimisés ? Budget travaux ? Prix max ?",
        important: true,
      },
      {
        id: 'red_flags_collegue',
        type: 'textarea',
        label: "Red flags vus par l'accompagnant",
        placeholder: 'Ce qu’il voit que je pourrais minimiser.',
        important: true,
      },
      blockerField('bloquant_debrief'),
    ],
  },
  {
    id: 'scoring',
    number: '13',
    title: 'Scoring final',
    critical: true,
    badge: 'Décision',
    intro: 'Note sévèrement. Une bonne moyenne ne compense pas un red flag bloquant.',
    fields: [
      ...scoringCriteria.map((criterion) => ({
        id: `score_${criterion.id}`,
        type: 'scale',
        label: criterion.label,
        required: true,
      })),
      {
        id: 'note_scoring',
        type: 'textarea',
        label: 'Pourquoi ces notes ?',
        placeholder: 'Explique surtout les notes sous 7 et les hésitations.',
        important: true,
      },
    ],
  },
  {
    id: 'decision_scenario',
    number: '14',
    title: 'Décision selon scénario',
    critical: true,
    badge: 'Verdict',
    intro: "Ne choisis pas le scénario qui t'arrange. Choisis celui que les faits imposent.",
    reminders: [
      'Scénario A : calme, sain, documents clairs, charges faibles, clauses non bloquantes, préférence nette.',
      "Scénario B : correct mais pas évident, défauts, chaudière ancienne, documents manquants, hésitation.",
      "Scénario C : bruit, humidité, eau mal évacuée, charges inconnues, clauses contraignantes, mauvais feeling.",
      "Question anti-panique : est-ce que je veux faire une offre parce que le bien est vraiment bon, ou parce que j'ai peur de rater ?",
      "Pas d'offre depuis le parking en panique : débrief, export ChatGPT, relecture à froid et financement avant envoi.",
      "Ne pas confondre opportunité rare et bonne décision.",
      "Décision interdite si : voisinage douteux, humidité douteuse, charges non écrites, clauses non écrites, pression temporelle ou peur de rater.",
    ],
    fields: [
      {
        id: 'scenario_retenu',
        type: 'choice',
        label: 'Scénario retenu',
        required: true,
        options: [
          { value: 'a', label: 'A - Offre possible' },
          { value: 'b', label: 'B - Temporiser', severity: 'warning' },
          { value: 'c', label: 'C - Ne pas acheter', severity: 'red' },
        ],
      },
      {
        id: 'note_decision',
        type: 'textarea',
        label: 'Justification honnête du scénario',
        placeholder: "Ce qui rend l'offre possible, ou ce qui impose de temporiser/stopper.",
        important: true,
      },
      {
        id: 'budget_travaux_estime',
        type: 'text',
        label: 'Budget travaux estimé',
        placeholder: 'Montant ou fourchette froide',
        important: true,
      },
      { id: 'cash_travaux_immediats', type: 'text', label: 'Cash : travaux immédiats', placeholder: '€' },
      { id: 'cash_cuisine_electro', type: 'text', label: 'Cash : cuisine / électroménager', placeholder: '€' },
      { id: 'cash_peinture_deco', type: 'text', label: 'Cash : peinture / déco', placeholder: '€' },
      { id: 'cash_exterieur', type: 'text', label: 'Cash : extérieur', placeholder: '€' },
      { id: 'cash_chaudiere_moyen_terme', type: 'text', label: 'Cash : chaudière à moyen terme', placeholder: '€' },
      { id: 'cash_emmenagement', type: 'text', label: 'Cash : frais déménagement', placeholder: '€' },
      { id: 'cash_meubles_luminaires', type: 'text', label: 'Cash : meubles / luminaires', placeholder: '€' },
      { id: 'cash_imprevus', type: 'text', label: 'Cash : imprévus / matelas sécurité', placeholder: '€' },
      { id: 'cash_total_prevoir', type: 'text', label: 'Total cash à prévoir', placeholder: '€', important: true },
      { id: 'comparaison_cout_mensuel', type: 'text', label: "Comparaison : coût mensuel ce bien vs l'autre bien", placeholder: 'Ce bien / autre bien' },
      { id: 'comparaison_surface', type: 'text', label: "Comparaison : surface ce bien vs l'autre bien", placeholder: 'Ce bien / autre bien' },
      { id: 'comparaison_dette', type: 'choice', label: 'Comparaison : dette avec ce bien', options: yesWarnNo },
      { id: 'comparaison_apport_conserve', type: 'choice', label: 'Comparaison : apport conservé avec ce bien', options: yesNo('warning') },
      { id: 'comparaison_stress_financier', type: 'choice', label: 'Stress financier de ce bien', options: weakMediumStrongRisk },
      { id: 'comparaison_liberte_future', type: 'choice', label: 'Liberté future avec ce bien', options: goodMediumWeak },
      { id: 'comparaison_patrimoine', type: 'choice', label: 'Comparaison : patrimoine créé par ce bien', options: yesNo('warning') },
      { id: 'regret_si_autre_bien', type: 'choice', label: "Si l'autre bien était attribué, regretterais-je d'avoir choisi ce bien ?", options: yesNoGoodNo },
      {
        id: 'decision_demain_matin',
        type: 'choice',
        label: 'Si je relis ça demain matin, serai-je fier de cette décision ?',
        options: [
          { value: 'oui', label: 'Oui' },
          { value: 'non', label: 'Non', severity: 'red' },
          { value: 'incertain', label: 'Je ne sais pas', severity: 'warning' },
        ],
      },
      {
        id: 'prix_max_froid',
        type: 'text',
        label: 'Prix maximum à froid',
        placeholder: 'Maximum à ne pas dépasser',
        important: true,
      },
      blockerField('bloquant_decision'),
    ],
  },
  {
    id: 'points_cles',
    number: '15',
    title: 'Les 7 points à ne surtout pas oublier',
    critical: true,
    badge: 'Blocants',
    intro: "Ces 7 points peuvent transformer une bonne opportunité en mauvaise décision.",
    reminders: [
      "Date limite d'offre / ordre d'arrivée.",
      'Voisinage / bruit / mitoyenneté.',
      'Humidité / traces noires / eaux pluviales.',
      'Chaudière / entretien / factures énergie.',
      'Charges ASL / lotissement / règlement.',
      'Clauses de revente / occupation / location future.',
      "Préférence réelle face à l'autre bien.",
    ],
    fields: [
      { id: 'check_offres', type: 'choice', label: "Date limite d'offre / ordre d'arrivée sécurisés ?", required: true, options: yesNo('red') },
      { id: 'check_voisinage', type: 'choice', label: 'Voisinage / bruit / mitoyenneté sécurisés ?', required: true, options: yesNo('red') },
      { id: 'check_humidite', type: 'choice', label: 'Humidité / eaux pluviales sécurisées ?', required: true, options: yesNo('red') },
      { id: 'check_chaudiere', type: 'choice', label: 'Chaudière / entretien / factures sécurisés ?', required: true, options: yesNo('warning') },
      { id: 'check_charges', type: 'choice', label: 'Charges / règlement sécurisés ?', required: true, options: yesNo('red') },
      { id: 'check_clauses', type: 'choice', label: 'Clauses de vente / location future sécurisées ?', required: true, options: yesNo('red') },
      { id: 'check_preference', type: 'choice', label: "Préférence réelle vs l'autre bien clarifiée ?", required: true, options: yesNo('warning') },
      {
        id: 'red_flags_finaux',
        type: 'textarea',
        label: 'Red flags finaux à ne pas minimiser',
        placeholder: 'Liste froide. Si un point bloque, il bloque.',
        important: true,
      },
    ],
  },
];
